Repository IBM/ibm-metering-multicloudui-operator, pull requests merged in 2020-07, with the labels that each got.

#1 init commit
  CONTRIBUTING.md
  Makefile
  README.md
  RELEASE.md
  SECURITY_CONTACTS
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  build/bin/entrypoint
  build/bin/user_setup
  cmd/manager/main.go
  codecov.yml
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/.hadolint.yml
  common/config/.yamllint.yml
  common/config/mdl.rb
  common/config/sass-lint.yml
  common/config/tslint.json
  common/scripts/.githooks/make_lint-all.sh
  common/scripts/.githooks/pre-commit
  common/scripts/codecov.sh
  common/scripts/config_docker.sh
  common/scripts/delete-csv.sh
  common/scripts/gobuild.sh
  common/scripts/install-operator-sdk.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  common/scripts/push-csv.sh
  deploy/crds/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringmulticloudui_cr.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  docs/development.md
  go.mod
  go.sum
  hack/boilerplate.go.txt
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/apis/apis.go
  pkg/apis/operator/group.go
  pkg/apis/operator/v1alpha1/common_sepc.go
  pkg/apis/operator/v1alpha1/doc.go
  pkg/apis/operator/v1alpha1/meteringmulticloudui_types.go
  pkg/apis/operator/v1alpha1/register.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_meteringmulticloudui.go
  pkg/controller/controller.go
  pkg/controller/meteringmulticloudui/meteringmulticloudui_controller.go
  pkg/resources/containers.go
  pkg/resources/reconcile.go
  pkg/resources/utils.go
  scripts/create-bundle.sh
  scripts/get-image-sha.sh
  scripts/rh-scan/certificate-crd.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#2 Shatt dev
  cmd/manager/main.go
Labels: approved, lgtm, size/XS

#4 fix some description issues
  common/scripts/push-csv.sh
  deploy/crds/operator.ibm.com_meteringmulticlouduis_crd.yaml
  deploy/olm-catalog/ibm-metering-multicloudui-operator/3.7.0/ibm-metering-multicloudui-operator.v3.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-metering-multicloudui-operator/3.7.0/operator.ibm.com_meteringmulticlouduis_crd.yaml
Labels: approved, lgtm, size/M

#5 update command string
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#6 add iam ns for security middleware
  pkg/resources/utils.go
Labels: approved, lgtm, size/XS

#7 update ot latest ubi image
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/S

#8 update to push to artifactory
  Makefile
  common/scripts/config_docker.sh
Labels: approved, lgtm, size/S
